import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createApp } from '../server.js';

test('room, upload, streaming and shared playback lifecycle', async t => {
  const server = await createApp();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const request = (route, options) => fetch(base + route, options);
  const create = await request('/api/rooms', { method: 'POST' });
  assert.equal(create.status, 201);
  const room = await create.json();
  assert.match(room.code, /^[A-F0-9]{6}$/);
  const route = `/api/rooms/${room.code}`;
  assert.equal((await request(route.toLowerCase())).status, 200);
  assert.equal((await request('/api/rooms/ZZZZZZ')).status, 404);
  assert.equal((await request(route + '/control', { method: 'POST', body: JSON.stringify({ action: 'play' }) })).status, 400);
  assert.equal((await request(route + '/tracks?name=fake.mp3', { method: 'POST', body: 'not audio' })).status, 400);
  assert.equal((await request(route + '/tracks?name=test.txt', { method: 'POST', body: 'ID3content' })).status, 400);
  const bytes = Buffer.from('ID3test-mp3-fixture');
  const upload = async name => {
    const response = await request(route + '/tracks?name=' + name, { method: 'POST', body: bytes });
    assert.equal(response.status, 201); return response.json();
  };
  await upload('first.mp3'); await upload('second.mp3');
  const queue = await upload('third.mp3');
  const [first, second] = queue.tracks;
  const stream = await request(route + '/tracks/' + first.id, { headers: { Range: 'bytes=3-6' } });
  assert.equal(stream.status, 206);
  assert.equal(stream.headers.get('content-type'), 'audio/mpeg');
  assert.equal(stream.headers.get('content-range'), `bytes 3-6/${bytes.length}`);
  assert.equal(await stream.text(), 'test');
  const suffix = await request(route + '/tracks/' + first.id, { headers: { Range: 'bytes=-7' } });
  assert.equal(await suffix.text(), 'fixture');
  assert.equal((await request(route + '/tracks/' + first.id, { headers: { Range: 'bytes=999-' } })).status, 416);
  const abort = new AbortController();
  const events = await request(route + '/events', { signal: abort.signal });
  const reader = events.body.getReader();
  const initial = new TextDecoder().decode((await reader.read()).value);
  assert.match(initial, /"listeners":1/);
  const control = async data => {
    const response = await request(route + '/control', { method: 'POST', body: JSON.stringify(data) });
    assert.equal(response.status, 200); return response.json();
  };
  assert.equal((await control({ action: 'play' })).playing, true);
  const update = new TextDecoder().decode((await reader.read()).value);
  assert.match(update, /"playing":true/);
  const seek = await control({ action: 'seek', position: 25 });
  assert.ok(seek.position >= 25 && seek.position < 26);
  assert.equal((await control({ action: 'pause' })).playing, false);
  await control({ action: 'play' });
  const results = await Promise.all([control({ action: 'ended', id: first.id }), control({ action: 'ended', id: first.id })]);
  for (const result of results) assert.equal(result.current, second.id);
  assert.equal((await request(route + '/control', { method: 'POST', body: JSON.stringify({ action: 'seek', position: -10 }) })).status, 400);
  assert.equal((await request('/api/rooms', { method: 'POST', headers: { Origin: 'https://another-site.example' } })).status, 403);
  abort.abort();
  const flacBytes = Buffer.from('fLaCtest-flac-fixture');
  for (const [name, body] of [['fake.flac', 'not audio'], ['renamed.flac', bytes], ['renamed.mp3', flacBytes]]) {
    assert.equal((await request(route + '/tracks?name=' + name, { method: 'POST', body })).status, 400);
  }
  const flacUpload = await request(route + '/tracks?name=Lossless.FLAC', { method: 'POST', body: flacBytes });
  assert.equal(flacUpload.status, 201);
  const flac = (await flacUpload.json()).tracks.at(-1);
  assert.equal(flac.name, 'Lossless');
  assert.equal(flac.contentType, 'audio/flac');
  const flacRoute = route + '/tracks/' + flac.id;
  const fullFlac = await request(flacRoute);
  assert.equal(fullFlac.headers.get('content-type'), 'audio/flac');
  assert.deepEqual(Buffer.from(await fullFlac.arrayBuffer()), flacBytes);
  const partialFlac = await request(flacRoute, { headers: { Range: 'bytes=4-7' } });
  assert.equal(partialFlac.status, 206);
  assert.equal(partialFlac.headers.get('content-type'), 'audio/flac');
  assert.equal(await partialFlac.text(), 'test');
  const headFlac = await request(flacRoute, { method: 'HEAD' });
  assert.equal(headFlac.headers.get('content-type'), 'audio/flac');
  assert.equal(Number(headFlac.headers.get('content-length')), flacBytes.length);
  assert.equal((await control({ action: 'select', id: flac.id })).current, flac.id);
  assert.equal((await request('/')).status, 200);
  assert.equal((await request('/app.js')).status, 200);
});
